version: '3.8'

services:
  postgres:
    container_name: follow-cep-db
    image: postgres
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: follow-cep-db
       PGDATA: /data/postgres
    volumes:
    - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d follow-cep-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  follow-cep-app:
    container_name: follow-cep-app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "npm run dev"]
    volumes:
     - ./:/usr/src/app
    ports:
      - 3333:3333
    depends_on:
       postgres:
         condition: service_healthy
  