version: '3.8'

services:
  postgres:
    container_name: follow-cep-db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
       PGDATA: /data/postgres
    volumes:
    - ./data/pg:/data/postgres
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

  follow-cep-app:
    container_name: follow-cep-app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "npm run dev"]
    volumes:
     - ./:/usr/src/app
    ports:
      - 3333:3333
    depends_on:
       postgres:
         condition: service_healthy
    env_file:
      - .env
  